### ISSUE TITLE
Chart not loading

### ISSUE THREAD

**Issue by Bodenrader** [hansenjohnson/WhaleMap#68]
When trying to zoom in, the chart detail will not load.

**Comment by hansenjohnson** [comment]
Thank you for flagging this! I think it's a problem with the Esri map provider service. It also looks like the Ocean Basemap is not working on the Leaflet Provider Demo page ([here](http://leaflet-extras.github.io/leaflet-providers/preview/#filter=Esri.OceanBasemap)). It may be due to Esri having updated the Ocean Basemap somewhat recently? I switched to using their latest version (with [this commit)](https://github.com/hansenjohnson/WhaleMap/commit/adff6b67264b46a6c2120554ad5e3d1471dbcefc) and it seems to have resolved the issue, though the new version doesn't seem quite as nice as the old one... I'm closing this now assuming it is resolved, but let me know if you continue to notice issues.

**Comment by hpettis** [comment]
Amy ran into this problem last week but when others went to check on it, no one could replicate her issue.

**Comment by hansenjohnson** [comment]
Thanks @hpettis. I think the same thing was happening to me. I suspect it's because many web browsers cache (i.e., locally save) that kind of map data, so you only see it's missing if you clear your cache or try to view an area that you haven't browsed before. Tricky!
